# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 730))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMaximumSize(QtCore.QSize(1100, 738))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 551, 671))
        self.label.setStyleSheet("border-style: solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(580, 40, 511, 671))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(550, 10, 41, 24))
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.ClearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(210, 10, 91, 24))
        self.ClearButton.setObjectName("ClearButton")
        self.LoadButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(10, 10, 91, 24))
        self.LoadButton.setObjectName("LoadButton")
        self.minusbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minusbutton.setGeometry(QtCore.QRect(510, 10, 31, 24))
        self.minusbutton.setObjectName("minusbutton")
        self.plusbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plusbutton.setGeometry(QtCore.QRect(600, 10, 31, 24))
        self.plusbutton.setObjectName("plusbutton")
        self.LoadButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LoadButton2.setGeometry(QtCore.QRect(110, 10, 91, 24))
        self.LoadButton2.setObjectName("LoadButton2")
        self.LoadButton2.setEnabled(False)
        self.SaveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(310, 10, 91, 24))
        self.SaveButton.setObjectName("SaveButton")
        self.SaveButton.setEnabled(True)
        self.AddButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(760, 10, 91, 24))
        self.AddButton.setObjectName("AddButton")
        self.AddButton.setEnabled(True)
        self.CountLines = QtWidgets.QLabel(parent=self.centralwidget)
        self.CountLines.setGeometry(QtCore.QRect(890, 20, 201, 20))
        self.CountLines.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.CountLines.setObjectName("CountLines")
        self.AddCountLines = QtWidgets.QLabel(parent=self.centralwidget)
        self.AddCountLines.setGeometry(QtCore.QRect(890, 0, 201, 20))
        self.AddCountLines.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.AddCountLines.setObjectName("AddCountLines")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.ClearButton.setText(_translate("MainWindow", "Очистить"))
        self.LoadButton.setText(_translate("MainWindow", "Документ"))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.plusbutton.setText(_translate("MainWindow", "+"))
        self.LoadButton2.setText(_translate("MainWindow", "Скан"))
        self.SaveButton.setText(_translate("MainWindow", "Сохранить"))
        self.AddButton.setText(_translate("MainWindow", "Добавить"))
        self.CountLines.setText(_translate("MainWindow", "Количество строк: 0"))
        self.AddCountLines.setText(_translate("MainWindow", "Количество добавленных строк: 0"))
